/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Gig } from "./Gig";
import { GigCountArgs } from "./GigCountArgs";
import { GigFindManyArgs } from "./GigFindManyArgs";
import { GigFindUniqueArgs } from "./GigFindUniqueArgs";
import { CreateGigArgs } from "./CreateGigArgs";
import { UpdateGigArgs } from "./UpdateGigArgs";
import { DeleteGigArgs } from "./DeleteGigArgs";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { Category } from "../../category/base/Category";
import { GigService } from "../gig.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Gig)
export class GigResolverBase {
  constructor(
    protected readonly service: GigService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Gig",
    action: "read",
    possession: "any",
  })
  async _gigsMeta(
    @graphql.Args() args: GigCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Gig])
  @nestAccessControl.UseRoles({
    resource: "Gig",
    action: "read",
    possession: "any",
  })
  async gigs(@graphql.Args() args: GigFindManyArgs): Promise<Gig[]> {
    return this.service.gigs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Gig, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Gig",
    action: "read",
    possession: "own",
  })
  async gig(@graphql.Args() args: GigFindUniqueArgs): Promise<Gig | null> {
    const result = await this.service.gig(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gig)
  @nestAccessControl.UseRoles({
    resource: "Gig",
    action: "create",
    possession: "any",
  })
  async createGig(@graphql.Args() args: CreateGigArgs): Promise<Gig> {
    return await this.service.createGig({
      ...args,
      data: {
        ...args.data,

        category: args.data.category
          ? {
              connect: args.data.category,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gig)
  @nestAccessControl.UseRoles({
    resource: "Gig",
    action: "update",
    possession: "any",
  })
  async updateGig(@graphql.Args() args: UpdateGigArgs): Promise<Gig | null> {
    try {
      return await this.service.updateGig({
        ...args,
        data: {
          ...args.data,

          category: args.data.category
            ? {
                connect: args.data.category,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Gig)
  @nestAccessControl.UseRoles({
    resource: "Gig",
    action: "delete",
    possession: "any",
  })
  async deleteGig(@graphql.Args() args: DeleteGigArgs): Promise<Gig | null> {
    try {
      return await this.service.deleteGig(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Order], { name: "orders" })
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "any",
  })
  async findOrders(
    @graphql.Parent() parent: Gig,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findOrders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Review], { name: "reviews" })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async findReviews(
    @graphql.Parent() parent: Gig,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviews(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Category, {
    nullable: true,
    name: "category",
  })
  @nestAccessControl.UseRoles({
    resource: "Category",
    action: "read",
    possession: "any",
  })
  async getCategory(@graphql.Parent() parent: Gig): Promise<Category | null> {
    const result = await this.service.getCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
